#!/bin/sh
exec lush $0
!#

;; a menu of demos

(when
  (or (member "-h" argv)
      (member "--help" argv))
  (writing "$stderr" 
   (render-brace-text 0 72
   '{<p> Synopsis: ,,(basename (car argv)) [-h]{<br>}
     A menu for starting the Lush demos with a mouse click
    }))
  (exit 0))

(ogre)

(de new-demo-btn (title prog desc nlin)
  (new row
    (new stdbutton "Run" (eval `(lambda (c) (sys (concat ,prog " &")))))
    (new stdbutton "Help" 
      (eval `(lambda (c) (repeat 72 (printf "=")) (printf "\n") (sys (concat ,prog " -h")))))
    (new string title)
    (new textpane 40 nlin desc)))

(setq win
  (new autowindowobject 10 10 100 100 "Simple GUI" 
    (new column
      (new-demo-btn "calculator     " "calculator" "A simple GUI calculator" 1)
      (new-demo-btn "lunar-lander   " "lunar-lander" "A Lunar Lander game with SDL" 1)
      (new-demo-btn "lushdoc        " "lushdoc" "Launches the Lush documentation browser" 1)
      (new-demo-btn "lushlife       " "lushlife" "Conway's Game of Life with SDL" 1)
      (new-demo-btn "sdl-bounce     " "sdl-bounce" '("Bounces a bunch of SDL sprites"
                                                      "around the screen") 2)
      (new-demo-btn "sdlgl-triangle " "sdlgl-triangle" '("Rotate an OpenGL object using"
	                                                   "the keyboard.") 2)
      (new-demo-btn "sdl-slimevolley" "sdl-slimevolley" "A modern version of Pong" 1)
      (new-demo-btn "show-image     " "show-image" "Shows an image (in any format)" 1)
      (new-demo-btn "simple-gui     " "simple-gui" "A simple demo of the Ogre GUI toolkit" 1)
      )))

(wait win)

  