<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<TITLE>Lush: Lisp Universal SHell</TITLE>
<meta name="keywords" content="Lush, Lisp, machine learning, neural nets, 
 computer vision, image processing, statistics, LeCun, Bottou, 
 Matlab, S+, xlispstat, Python, SDL, DjVu">
<meta name="description" 
  content="Lush: the programming language for researchers">

#include "[[INCLUDE]]/style.inc"

</head>

<body bgcolor="#606060" link="[[blue]]" vlink="[[blue]]" alink="[[blue]]">
<script language="javascript">
<!--//

if (document.images) {
  var bullet_on = new Image();
  bullet_on.src = "[[IMAGES]]/menu-button-dn-160x50.gif";
  var bullet_off = new Image();
  bullet_off.src = "[[IMAGES]]/menu-button-up-160x50.gif";
}
function select(i) {
  if (document.images) {
    document.images[i].src = bullet_on.src;
  }
}
function deselect(i) {
  if (document.images) {
    document.images[i].src = bullet_off.src;
  }
}
//-->
</script>


<table bgcolor="[[beige]]" border=0 cellpadding=0 cellspacing=0 valign="top">

<tr>
<td rowspan=3 width=160 valign="top" background="[[IMAGES]]/menu-button-blnk-160x50.gif">
#include "[[MENU_INC]]"
</td>
<td colspan=3 background="[[IMAGES]]/paper-tile-320x100.gif" align=center>
[[cleargif(8,8)]]<br>
[[thebanner]]
<p>
<HR SIZE="1" NoShade>
#include "[[TABS_INC]]"
</td>
<td rowspan=3 background="[[IMAGES]]/paper-tile-rght-42x100.gif">
[[cleargif(42,1)]]
</td>
</tr>

<tr><td valign=top><table width="100%" border=0 cellpadding=3 cellspacing=0>
<tr>
<td background="[[IMAGES]]/paper-corner-ul.gif">[[cleargif(2,2)]]</td>
<td background="[[IMAGES]]/paper-hline.gif">[[cleargif(2,2)]]</td>
<td background="[[IMAGES]]/paper-corner-ur.gif">[[cleargif(2,2)]]</td>
</tr>

<tr>
<td background="[[IMAGES]]/paper-vline.gif">[[cleargif(2,600)]]</td>
<td width=100% valign=top>
