
</td>
<td background="[[IMAGES]]/paper-vline.gif">[[cleargif(2,2)]]</td>
</tr>

<tr>
<td background="[[IMAGES]]/paper-corner-ll.gif">[[cleargif(2,2)]]</td>
<td background="[[IMAGES]]/paper-hline.gif">[[cleargif(2,2)]]</td>
<td background="[[IMAGES]]/paper-corner-lr.gif">[[cleargif(2,2)]]</td>
</tr>

</table></td></tr>

<tr>
<td colspan=3 background="[[IMAGES]]/paper-tile-320x100.gif" align=center>
<font color="[[blue]]">Lush</font>
</td>
</tr>

</table>

</body>
</html>
