

<table width=160 border="0" cellspacing="0" cellpadding="0">
[[menubutton(Lush Home,[[HOME]]/index.html)]]
[[menubutton(News,[[HOME]]/news.html)]]
[[menubutton(Screenshots,[[HOME]]/screenshots.html)]]
[[menubutton(Downloads,[[SHOWFILES]])]]
[[menubutton(Documentation,doc.html)]]
[[menubutton(FAQs,faq.html)]]
[[menubutton(Project Page,[[PROJECT]])]]
[[menubutton(CVS Tree,[[CVS_LUSH]])]]
[[menubutton(History/Credits,[[HOME]]/credits.html)]]
[[menubutton(Links/Contacts,[[HOME]]/links.html)]]
[[menubutton(To Do List,[[HOME]]/todo.html)]]
[[menuspace(10)]]
[[menusep(50,<A href="http://sourceforge.net"> <IMG src="http://sourceforge.net/sflogo.php?group_id=32953" width="88" height="31" border="0" alt="SourceForge Logo"></A>)]]
</table>
