	<style type="text/css">
	<!--
	OL,UL,P,BODY,TD,TR,TH,FORM { font-family: verdana,arial,helvetica,sans-serif; font-size:small; color: #000000; }

	H1 { font-size: x-large; font-family: verdana,arial,helvetica,sans-serif; }
	H2 { font-size: large; font-family: verdana,arial,helvetica,sans-serif; }
	H3 { font-size: medium; font-family: verdana,arial,helvetica,sans-serif; }
	H4 { font-size: small; font-family: verdana,arial,helvetica,sans-serif; }
	H5 { font-size: x-small; font-family: verdana,arial,helvetica,sans-serif; }
	H6 { font-size: xx-small; font-family: verdana,arial,helvetica,sans-serif; }

	PRE,TT { font-family: courier,sans-serif }

	SPAN.center { text-align: center }
	SPAN.boxspace { font-size: 2pt; }
	SPAN.osdn {font-size: xx-small; font-family: verdana,arial,helvetica,sans-serif;}
	SPAN.search {font-size: xx-small; font-family:  verdana,arial,helvetica,sans-serif;}
	SPAN.slogan {font-size: large; font-weight: bold; font-family: verdana,arial,helvetica,sans-serif;}
	SPAN.footer {font-size: xx-small; font-family: verdana,arial,helvetica,sans-serif;}

        SPAN.menubutton {font-size: 12px; text-decoration: none; }
        SPAN.menubutton:hover { color: #cc0000; }

	.tabs { color: [[blue]]; }
	.tabs:visited { color: [[blue]]; }
	.tabs:hover { font-weight: bold; }
	.tabselect { color: #000000; font-weight: bold; }
	.tabselect:visited { font-weight: bold;}
	.tabselect:hover { color:#FF0000; font-weight: bold; }
	-->
	</style>

